# NumPy

Based on original notebook from [Om Salafia](https://github.com/omsharansalafia/intropython)

[Numpy](http://www.numpy.org/) is one of the most useful Python packages and it represents one of the core libraries for scientific computing in Python. It provides a high-performance multidimensional array object and tools for working with it. Inside a Python script, everything starts with an import statement:

In [1]:
import numpy as np # we imported numpy with the name np (so that we do not have to write the full name all the time)

## NumPy Arrays

A numpy array is a grid of values. Differently from Python lists, values must to be all of the same type. The number of dimensions is the rank of the array, while the shape of an array is a tuple of integers giving the size of the array along each dimension.

### Array creation

We can initialize numpy arrays from nested Python lists, and access elements using square brackets `[ ]`:

In [2]:
a = np.array([1, 2, 3])   # array of rank 1 (vettore)
b = np.array([[1, 2, 3],[4, 5, 6]])   # array of rank 2 (2 dimensional matrix)
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints a Tuple (note round parenthesis) with one element, the length of the array
print(b.shape)            # Prints a Tuple (note round parenthesis) with two elements, the length of the array in the 2 dimensions
print(a[0], a[1], a[2])   
a[0] = 5                  # Change an element of the array
print(a)

print("\n")
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b)
print(b.shape)                     # Prints a Tuple with two elements, the length along each axis
print(b[0, 0], b[0, 1], b[1, 0])
print(b[1,1])

<class 'numpy.ndarray'>
(3,)
(2, 3)
1 2 3
[5 2 3]


[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4
5


Indexing can also be achieved with single `[ ]` for each dimension:

In [3]:
print(b[0][0], b[0][1], b[1][0])

1 2 4


NumPy has many functions for array creation, for example:

In [4]:
a = np.zeros((2,2))   # Create an array of all zeros
print('a=', a,"\n")              

b = np.ones(2)    # Create an array of all ones
print('b=', b,"\n")              

c = np.full([2,2], 7)  # Create an array filled with the given value
print('c=', c,"\n")               

d = np.eye(2)         # Create a 2x2 identity matrix
print('d=', d,"\n")

e = np.arange(3,5,0.5) # Create an array containing numbers between 3 and 5, separated by 0.5
print('e=', e,"\n")

f = np.linspace(3,5,6) # Create an array containing 6 linearly spaced numbers between 3 and 5
print('f=', f,"\n")

g = np.logspace(2,5,4) # Create an array containing 4 log-spaced numbers between 10**2 and 10**5
print('g=',g, '\n')

h = 3**np.arange(2,6,1)
print('h=',h)

i = 10**np.linspace(2,5,4)
print('i=',i)

a= [[0. 0.]
 [0. 0.]] 

b= [1. 1.] 

c= [[7 7]
 [7 7]] 

d= [[1. 0.]
 [0. 1.]] 

e= [3.  3.5 4.  4.5] 

f= [3.  3.4 3.8 4.2 4.6 5. ] 

g= [   100.   1000.  10000. 100000.] 

h= [  9  27  81 243]
i= [   100.   1000.  10000. 100000.]


### Array indexing: slicing

Slicing is a quick method to extract parts of an array. For multidimensional objects, you must specify a slice for each dimension of the array. Slices are specified by the starting index (included), final index (not included) and increment step, i.e. `a[i:j:step]`, all being optional.

In [5]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("the shape of a:",a.shape)
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
print(a, '\n')
b = a[:2, 1:3]
print(b,"\n")

the shape of a: (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[2 3]
 [6 7]] 



The `ravel()` method can be used to flatten an array (turn it one-dimensional)

In [6]:
print('a=',a,'\n')
a_flat = a.ravel()
print('a_flat=',  a_flat)

a= [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

a_flat= [ 1  2  3  4  5  6  7  8  9 10 11 12]


Negative numbers can be used to access elements backwards, starting from the end of the array. For example, `a_flat[-1]` is the last element of `a_flat`:

In [7]:
print(a_flat[-1])

12


**NOTE: pay attention that when setting two arrays to be equal you are actually creating a pointer**:

In [8]:
xx = np.array([1,2]) # First array
print("xx =",xx) 
yy = xx              # Slice, in this case a full slice, i.e. equality
print("yy =",yy)
xx[0] = 3            # First array is modified, also yy is modified

print("\nxx =",xx)
print("yy =",yy) 

xx = [1 2]
yy = [1 2]

xx = [3 2]
yy = [3 2]


If you want to avoid this behaviour you need to create a new numpy array using the copy function:

In [9]:
xx = np.array([1,2])
print("xx =",xx)
yy = np.copy(xx)
print("yy =",yy)
xx[0] = 3

print("\nxx =",xx)
print("yy =",yy) 

xx = [1 2]
yy = [1 2]

xx = [3 2]
yy = [1 2]


### Array indexing: boolean

In [10]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a, '\n')
print(a.shape, '\n')

bool_idx = (a >= 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

bool_idx2 = (a < 5)
            
print(bool_idx,"\n")
print(bool_idx2,"\n")

[[1 2]
 [3 4]
 [5 6]] 

(3, 2) 

[[False  True]
 [ True  True]
 [ True  True]] 

[[ True  True]
 [ True  True]
 [False False]] 



In [11]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx],"\n")  

# We can do all of the above in a single concise statement:
print(a[a >= 2],"\n")

print(a[bool_idx & bool_idx2])
print(a[(a >=2) & (a < 5)])

[2 3 4 5 6] 

[2 3 4 5 6] 

[2 3 4]
[2 3 4]


## Array math

Basic mathematical functions operate elementwise on arrays, i.e. operate on each element separately (**element-wise operation**). We can perform scalar multiplication:

In [12]:
y = np.array([1,2,3])
alpha = 3.5

print(alpha*y)

[ 3.5  7.  10.5]


or apply functions to arrays:

In [13]:
x2 = np.array([1,4,9,25])
x = np.sqrt(x2) # Compute the square root
x3 = x**3       # Compute the cube
print(x)
print(x3)

[1. 2. 3. 5.]
[  1.   8.  27. 125.]


Mathematical functions are available both as operator and as functions in the numpy module:

In [14]:
print(x + x2)
print(np.add(x, x2))

[ 2.  6. 12. 30.]
[ 2.  6. 12. 30.]


In [15]:
print('x=',x)
print('x2=', x2, '\n')

print(x * x2)
print(np.multiply(x, x2), '\n')

print(np.dot(x,x2))

x= [1. 2. 3. 5.]
x2= [ 1  4  9 25] 

[  1.   8.  27. 125.]
[  1.   8.  27. 125.] 

161.0


Of course arrays must have the same shape:

In [16]:
y = np.array([1,2])
print(x*y)

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

The actual requirement is that *the last axes have the same length*, or alternatively that one has *unit length*

In [17]:
x = np.arange(1,5,1)
y = np.ones([8,4])
print(x)
print(x.shape)
print(y)
print(y.shape, '\n')
print(x*y)

[1 2 3 4]
(4,)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(8, 4) 

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [18]:
z = np.array([[1],[10],[100],[1000]])
print(z.shape)
print(x*z)

(4, 1)
[[   1    2    3    4]
 [  10   20   30   40]
 [ 100  200  300  400]
 [1000 2000 3000 4000]]


## Boolean arrays

Boolean arrays can be created using the usual comparison operators, such as `>` (greater), `<` (smaller), `==` (equal to) and `!=` (not equal to), and they can be combined using the bitwise operators `&` (and), `|` (or), and `~` (not):

In [19]:
a = np.arange(0,10,1)
print(a)

b = a<5
print(b, '\n')

c = a>3
print(b & c)

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False] 

[False False False False  True False False False False False]


Boolean arrays can be used to select elements in an array:


In [20]:
print(a[b])
print(a[b & c])

[0 1 2 3 4]
[4]


## Other types

In [21]:
a = np.array([1,2,3],dtype=int)
b = np.array(['a','b','c'],dtype=str)
c = np.array([1,2,3],dtype=str)
print(a)
print(b)
print(c)

[1 2 3]
['a' 'b' 'c']
['1' '2' '3']


## Some additional functions & further reference

Finally, Numpy provides many useful functions for performing computations on arrays, like sum, inner products and trasposition (see [here](https://docs.scipy.org/doc/numpy/reference/routines.math.html) for a complete list):

In [22]:
x = np.array([[1,2],[3,4]])
print('x=', x, '\n')

print('Sum=', np.sum(x), '\n')  # Compute sum of all elements
print(np.sum(x, axis=0), '\n')  # Compute sum of each column
print(np.sum(x, axis=1))  # Compute sum of each row

x= [[1 2]
 [3 4]] 

Sum= 10 

[4 6] 

[3 7]


In [23]:
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors
print(v.dot(w))
print(np.dot(v, w))

219
219


In [24]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x,"\n")    
print(x.T)  # Transposition, i.e. switch between rows and columns

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 4 7]
 [2 5 8]
 [3 6 9]]
